development:
  adapter: postgresql
  allowed_request_origins:
    - "http://localhost:3000"   # Adjust port if necessary
    - "http://127.0.0.1:3000"
    - "http://localhost"        # Allow direct localhost access
    - "http://127.0.0.1"




test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: test2_production
